# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsection',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.DeleteModel(
            name='PostSection',
        ),
    ]
