# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160426_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('code', models.TextField(blank=True, max_length=600, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsection', to='blog.Post')),
            ],
        ),
    ]
