# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='pic', upload_to='photos'),
        ),
    ]
