# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='pic', upload_to='../photos'),
        ),
    ]
