# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsection',
            name='code',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
